---
- name: Before symlink | Bokehlicious | Configure Laravel
  include_tasks: ./before_symlink/backend/laravel.yml
  when: backend ==  laravel
- name: Before symlink | Bokehlicious | Configure Symfony
  include_tasks: ./before_symlink/backend/symfony.yml
  when: backend == symfony