---
- name: Deploy Bokehlicious to Prod server
  vars_files:
    - parameters.yml
  hosts: all
  remote_user: "{{ superuser }}"
  become: true
  become_method: sudo
  tasks:
    - include_role:
        name: bokehlicious