---
- name: Install Server
  hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: parameters.yml
    - name: "USER | Add user {{ superuser }}"
      user:
        name: "{{ superuser }}"
        shell: /bin/bash
        state: present
    - name: "USER | Add SSH key for user {{ superuser }}"
      authorized_key:
        user: "{{ superuser }}"
        state: present
        key: "{{ lookup('file', path_to_ssh_key) }}"
      vars:
        path_to_ssh_key: "{{ superuser_ssh_key }}"
    - name: APT | Update system
      apt:
        upgrade: dist
        update_cache: yes
        autoclean: yes
    - include_role:
        name: firewall
    - include_role:
        name: tools
    - include_role:
        name: php
    - include_role:
        name: database
    - include_role:
        name: nodejs
    - include_role:
        name: nginx