---
- name: Install Server
  vars_files:
    - parameters.yml
  hosts: all
  remote_user: "{{ superuser }}"
  become: true
  become_method: sudo
  tasks:
    - name: APT | Update system
      apt:
        upgrade: dist
        update_cache: yes
        autoclean: yes
    - include_role:
        name: firewall
    - include_role:
        name: tools
    - include_role:
        name: php
    - include_role:
        name: database
    - include_role:
        name: nodejs
    - include_role:
        name: nginx