---
- name: NGINX | Remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
- name: NGINX | Remove nginx.conf
  file:
    path: /etc/nginx/nginx.conf
    state: absent
- name: NGINX | Create partial folder
  file:
    path: /etc/nginx/partials
    state: directory
    mode: 0755
- name: NGINX | Add general.conf
  template:
    src: general.conf.j2
    dest: /etc/nginx/partials/general.conf
- name: NGINX | Add nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: NGINX | Add php_fastcgi.conf
  template:
    src: php_fastcgi.conf.j2
    dest: /etc/nginx/partials/php_fastcgi.conf