---
#Mysql
- name: mysql restart
  service:
    name: mysql
    state: restarted

- name: mysql upgrade
  command: mysql_upgrade

# Nginx
- name: nginx restart
  service:
    name: mysql
    state: restarted
    enabled: yes
