---
- name: Before symlink | Laravel | Composer install
  command: "composer install"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: Before symlink | Laravel | Generate App key
  shell: "php artisan key:generate --show > {{ ansistrano_shared_path }}/app_key"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
    creates: "{{ ansistrano_shared_path }}/app_key"
- name: Before symlink | Laravel | Get App key
  command: "cat {{ ansistrano_shared_path }}/app_key"
  register: app_key
- name: Before symlink | Laravel | Generate .env file
  template:
    src: env.j2
    dest: "{{ ansistrano_shared_path }}/.env"