---
- name: Bokehlicious | Include Ansistrano variables
  include_vars: ansistrano.yml
- name: Bokehlicious | Start deployment
  apt:
    upgrade: dist
    update_cache: yes
    autoclean: yes
- name: Bokehlicious | Configure User
  include_tasks: user.yml
- name: Bokehlicious | Configure SSH
  include_tasks: ssh.yml
- name: Bokehlicious | Update Nginx server
  include_tasks: nginx.yml
- name: Bokehlicious | Update Database
  include_tasks: database.yml
  # Restart Mysql
  notify: mysql restart
- name: Bokehlicious | Update PHP
  include_tasks: php.yml
- include_role:
    name: ansistrano.deploy
    apply:
      remote_user: "{{ username }}"
      become: no
      become_method: sudo
