---
- name: "After symlink | NPM | Install dependencies"
  command: npm install
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: "After symlink | NPM | Compile assets"
  command: npm run production
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"