---
- name: "{{ project_name }} | NGINX | Create logs folder"
  file:
    path: "/var/log/nginx/{{ project_name }}"
    state: directory
    mode: 0755
- name: "{{ project_name }} | NGINX | Check if default.conf is present"
  stat:
    path: /etc/nginx/conf.d/default.conf
  register: default_conf
- name: "{{ project_name }} | NGINX | Add new default.conf"
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  when: default_conf.stat.exists == false
- name: "{{ project_name }} | NGINX | Add {{ project_name }}.conf"
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/conf.d/{{ project_name }}.conf"
  # Test the conf (it will add the log files) and restart Web services (PHP & Nginx)
  notify:
    - nginx test
    - restart web services