---
- name: "PHP | Update all packages (Debian {{ debian_codename }})"
  apt:
    update_cache: yes
- name: "PHP | Add dependencies for PHP version (Debian {{ debian_codename }})"
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
    state: present
- name: "PHP | Add PHP signing key (Debian {{ debian_codename }})"
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
- name: PHP | Add repository ondrej/php repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ debian_codename }} main"
- name: "PHP | Install PHP{{ php_version }}-fpm + PHP Modules "
  apt:
    # Laravel needs this PHP modules : OpenSSL, PDO, MBString, Tokenizer, XML, CType, JSON, BCMatth
    name:
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-mysql"
    state: present
- name: PHP | Install Composer
  shell: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    mv composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
- name: PHP | Update PHP.ini
  lineinfile:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line}}"
  with_items:
    - { regexp: '^;date.timezone =', line: 'date.timezone=UTC'}
    - { regexp: '^memory_limit =', line: 'memory_limit = 1024M'}
    - { regexp: '^upload_max_filesize =', line: 'upload_max_filesize = 20M'}
    - { regexp: '^post_max_size =', line: 'post_max_size = 100M'}
  notify: php restart
- name: PHP | Remove useless packages from the cache
  apt:
    autoclean: yes
- name: PHP | Remove dependencies that are no longer required
  apt:
    autoremove: yes