---
# To check Amdin user privilege => SHOW GRANTS FOR 'root'@'localhost';
- name: Database | Create Admin User
  mysql_user:
    name: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL'
    state: present
- name: Database | Remove All Anonymous users
  mysql_user:
    name: ""
    host_all: yes
    state: absent
# To check all user => select user, host from mysql.user;
- name: Database | Create All users
  mysql_user:
    name: "{{ item.username }}"
    password: "{{ item.password  | default('pwd')}}"
    priv: "{{ item.username }}.*:ALL"
    state: present
  loop: "{{ mysql_users }}"
